//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\TeuchiUdonParser.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace akanevrc.TeuchiUdon.Editor.Compiler {

    #pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TeuchiUdonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface ITeuchiUdonParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTarget([NotNull] TeuchiUdonParser.TargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTarget([NotNull] TeuchiUdonParser.TargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] TeuchiUdonParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] TeuchiUdonParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarBindTopStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarBindTopStatement([NotNull] TeuchiUdonParser.VarBindTopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarBindTopStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarBindTopStatement([NotNull] TeuchiUdonParser.VarBindTopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprTopStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprTopStatement([NotNull] TeuchiUdonParser.ExprTopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprTopStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprTopStatement([NotNull] TeuchiUdonParser.ExprTopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InitVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitVarAttr([NotNull] TeuchiUdonParser.InitVarAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InitVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitVarAttr([NotNull] TeuchiUdonParser.InitVarAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExportVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExportVarAttr([NotNull] TeuchiUdonParser.ExportVarAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExportVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExportVarAttr([NotNull] TeuchiUdonParser.ExportVarAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SyncVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSyncVarAttr([NotNull] TeuchiUdonParser.SyncVarAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SyncVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSyncVarAttr([NotNull] TeuchiUdonParser.SyncVarAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LinearVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinearVarAttr([NotNull] TeuchiUdonParser.LinearVarAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LinearVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinearVarAttr([NotNull] TeuchiUdonParser.LinearVarAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SmoothVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSmoothVarAttr([NotNull] TeuchiUdonParser.SmoothVarAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SmoothVarAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSmoothVarAttr([NotNull] TeuchiUdonParser.SmoothVarAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>InitExprAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.exprAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitExprAttr([NotNull] TeuchiUdonParser.InitExprAttrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>InitExprAttr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.exprAttr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitExprAttr([NotNull] TeuchiUdonParser.InitExprAttrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.varBind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarBind([NotNull] TeuchiUdonParser.VarBindContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.varBind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarBind([NotNull] TeuchiUdonParser.VarBindContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnitVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitVarDecl([NotNull] TeuchiUdonParser.UnitVarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnitVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitVarDecl([NotNull] TeuchiUdonParser.UnitVarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SingleVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleVarDecl([NotNull] TeuchiUdonParser.SingleVarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SingleVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleVarDecl([NotNull] TeuchiUdonParser.SingleVarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>TupleVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTupleVarDecl([NotNull] TeuchiUdonParser.TupleVarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>TupleVarDecl</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTupleVarDecl([NotNull] TeuchiUdonParser.TupleVarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.qualifiedVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedVar([NotNull] TeuchiUdonParser.QualifiedVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.qualifiedVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedVar([NotNull] TeuchiUdonParser.QualifiedVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] TeuchiUdonParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] TeuchiUdonParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnUnitStatement([NotNull] TeuchiUdonParser.ReturnUnitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnUnitStatement([NotNull] TeuchiUdonParser.ReturnUnitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ReturnValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnValueStatement([NotNull] TeuchiUdonParser.ReturnValueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ReturnValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnValueStatement([NotNull] TeuchiUdonParser.ReturnValueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueUnitStatement([NotNull] TeuchiUdonParser.ContinueUnitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueUnitStatement([NotNull] TeuchiUdonParser.ContinueUnitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ContinueValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueValueStatement([NotNull] TeuchiUdonParser.ContinueValueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ContinueValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueValueStatement([NotNull] TeuchiUdonParser.ContinueValueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakUnitStatement([NotNull] TeuchiUdonParser.BreakUnitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakUnitStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakUnitStatement([NotNull] TeuchiUdonParser.BreakUnitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BreakValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakValueStatement([NotNull] TeuchiUdonParser.BreakValueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BreakValueStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakValueStatement([NotNull] TeuchiUdonParser.BreakValueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LetBindStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetBindStatement([NotNull] TeuchiUdonParser.LetBindStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LetBindStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetBindStatement([NotNull] TeuchiUdonParser.LetBindStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExprStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStatement([NotNull] TeuchiUdonParser.ExprStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExprStatement</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStatement([NotNull] TeuchiUdonParser.ExprStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ThisLiteralExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisLiteralExpr([NotNull] TeuchiUdonParser.ThisLiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ThisLiteralExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisLiteralExpr([NotNull] TeuchiUdonParser.ThisLiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnitBlockExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitBlockExpr([NotNull] TeuchiUdonParser.UnitBlockExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnitBlockExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitBlockExpr([NotNull] TeuchiUdonParser.UnitBlockExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpr([NotNull] TeuchiUdonParser.LogicalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalAndExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpr([NotNull] TeuchiUdonParser.LogicalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignExpr([NotNull] TeuchiUdonParser.AssignExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignExpr([NotNull] TeuchiUdonParser.AssignExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EvalVarExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalVarExpr([NotNull] TeuchiUdonParser.EvalVarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EvalVarExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalVarExpr([NotNull] TeuchiUdonParser.EvalVarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PostfixExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpr([NotNull] TeuchiUdonParser.PostfixExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PostfixExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpr([NotNull] TeuchiUdonParser.PostfixExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualityExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpr([NotNull] TeuchiUdonParser.EqualityExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualityExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpr([NotNull] TeuchiUdonParser.EqualityExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ValueBlockExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueBlockExpr([NotNull] TeuchiUdonParser.ValueBlockExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ValueBlockExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueBlockExpr([NotNull] TeuchiUdonParser.ValueBlockExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpr([NotNull] TeuchiUdonParser.LiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpr([NotNull] TeuchiUdonParser.LiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultiplicationExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicationExpr([NotNull] TeuchiUdonParser.MultiplicationExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultiplicationExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicationExpr([NotNull] TeuchiUdonParser.MultiplicationExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ShiftExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpr([NotNull] TeuchiUdonParser.ShiftExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ShiftExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpr([NotNull] TeuchiUdonParser.ShiftExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EvalSingleFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalSingleFuncExpr([NotNull] TeuchiUdonParser.EvalSingleFuncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EvalSingleFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalSingleFuncExpr([NotNull] TeuchiUdonParser.EvalSingleFuncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AccessExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessExpr([NotNull] TeuchiUdonParser.AccessExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AccessExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessExpr([NotNull] TeuchiUdonParser.AccessExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EvalUnitFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalUnitFuncExpr([NotNull] TeuchiUdonParser.EvalUnitFuncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EvalUnitFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalUnitFuncExpr([NotNull] TeuchiUdonParser.EvalUnitFuncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EvalTupleFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvalTupleFuncExpr([NotNull] TeuchiUdonParser.EvalTupleFuncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EvalTupleFuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvalTupleFuncExpr([NotNull] TeuchiUdonParser.EvalTupleFuncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NameOfExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameOfExpr([NotNull] TeuchiUdonParser.NameOfExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NameOfExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameOfExpr([NotNull] TeuchiUdonParser.NameOfExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RelationExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationExpr([NotNull] TeuchiUdonParser.RelationExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RelationExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationExpr([NotNull] TeuchiUdonParser.RelationExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RangeExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeExpr([NotNull] TeuchiUdonParser.RangeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RangeExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeExpr([NotNull] TeuchiUdonParser.RangeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConditionalExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpr([NotNull] TeuchiUdonParser.ConditionalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConditionalExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpr([NotNull] TeuchiUdonParser.ConditionalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncExpr([NotNull] TeuchiUdonParser.FuncExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FuncExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncExpr([NotNull] TeuchiUdonParser.FuncExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixExpr([NotNull] TeuchiUdonParser.PrefixExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PrefixExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixExpr([NotNull] TeuchiUdonParser.PrefixExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConditionalOrExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalOrExpr([NotNull] TeuchiUdonParser.ConditionalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConditionalOrExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalOrExpr([NotNull] TeuchiUdonParser.ConditionalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpr([NotNull] TeuchiUdonParser.LogicalOrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalOrExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpr([NotNull] TeuchiUdonParser.LogicalOrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AdditionExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionExpr([NotNull] TeuchiUdonParser.AdditionExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AdditionExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionExpr([NotNull] TeuchiUdonParser.AdditionExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LetInBindExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetInBindExpr([NotNull] TeuchiUdonParser.LetInBindExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LetInBindExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetInBindExpr([NotNull] TeuchiUdonParser.LetInBindExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConditionalAndExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalAndExpr([NotNull] TeuchiUdonParser.ConditionalAndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConditionalAndExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalAndExpr([NotNull] TeuchiUdonParser.ConditionalAndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CoalescingExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCoalescingExpr([NotNull] TeuchiUdonParser.CoalescingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CoalescingExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCoalescingExpr([NotNull] TeuchiUdonParser.CoalescingExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] TeuchiUdonParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] TeuchiUdonParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalXorExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalXorExpr([NotNull] TeuchiUdonParser.LogicalXorExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalXorExpr</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalXorExpr([NotNull] TeuchiUdonParser.LogicalXorExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.argExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgExpr([NotNull] TeuchiUdonParser.ArgExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.argExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgExpr([NotNull] TeuchiUdonParser.ArgExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnitLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitLiteral([NotNull] TeuchiUdonParser.UnitLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnitLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitLiteral([NotNull] TeuchiUdonParser.UnitLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NullLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullLiteral([NotNull] TeuchiUdonParser.NullLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NullLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullLiteral([NotNull] TeuchiUdonParser.NullLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BoolLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolLiteral([NotNull] TeuchiUdonParser.BoolLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BoolLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolLiteral([NotNull] TeuchiUdonParser.BoolLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerLiteral([NotNull] TeuchiUdonParser.IntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerLiteral([NotNull] TeuchiUdonParser.IntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>HexIntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHexIntegerLiteral([NotNull] TeuchiUdonParser.HexIntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>HexIntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHexIntegerLiteral([NotNull] TeuchiUdonParser.HexIntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BinIntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinIntegerLiteral([NotNull] TeuchiUdonParser.BinIntegerLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BinIntegerLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinIntegerLiteral([NotNull] TeuchiUdonParser.BinIntegerLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RealLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRealLiteral([NotNull] TeuchiUdonParser.RealLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RealLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRealLiteral([NotNull] TeuchiUdonParser.RealLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CharacterLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterLiteral([NotNull] TeuchiUdonParser.CharacterLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CharacterLiteral</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterLiteral([NotNull] TeuchiUdonParser.CharacterLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>RegularString</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegularString([NotNull] TeuchiUdonParser.RegularStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>RegularString</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegularString([NotNull] TeuchiUdonParser.RegularStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VervatiumString</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVervatiumString([NotNull] TeuchiUdonParser.VervatiumStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VervatiumString</c>
	/// labeled alternative in <see cref="TeuchiUdonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVervatiumString([NotNull] TeuchiUdonParser.VervatiumStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TeuchiUdonParser.thisLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisLiteral([NotNull] TeuchiUdonParser.ThisLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TeuchiUdonParser.thisLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisLiteral([NotNull] TeuchiUdonParser.ThisLiteralContext context);
}
} // namespace akanevrc.TeuchiUdon.Editor.Compiler
