[package]
name = "teuchiudon-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
function_name = "0.3.0"
itertools = "0.10.5"
nom = { version = "7.1.1", features = ["alloc"] }

[dev-dependencies]
assert_matches = "1.5.0"
